### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by yirkajk**

### CODE REVIEW

**Comment by yirkajk** [comment]
@math1um I included your email and a link to your website as "contact information". Is this okay?
@nvcleemp Would you like to include any contact information?

**Comment by math1um** [comment]
fine by me!

**Comment by nvcleemp** [comment]
I have no strong feelings neither towards including my contact information and not including my contact information.

**Comment by math1um** [comment]
Then put Nico's info too. He started the project - and the association with the Project is important in many ways.

**Pull request merged**
